Run("notepad.exe","C:\Windows")
Sleep(2000)
Send("Welcome to AutoIt tool , It is used for Windows Automation")
Send("{ENTER}")
Send("This tool used Basic Language for Writing testcases ")
Sleep(2000)
WinClose("*Untitled - Notepad")
Sleep(2000)
ControlClick("Notepad","Do&n't Save","Button2")
Sleep(2000)